
spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/sakila
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.hand.exam1.entity
  mapper-locations: classpath:mapper/*.xml
